logging:
  path: /usr/local/jars/log/${spring.application.name}
spring:
  application:
    name: msa-weather-collection-server
#    redis auth
  redis:
    password: 123456
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
feign:
  client:
    config:
      feignName:
        connectionTimeout: 50000
        readTimeout: 50000